spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/young
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  messages:
    encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true